### ISSUE TITLE
500 error - Retrieving SF data

### ISSUE THREAD

**Issue by apollondor** [mjavier2k/solidfire-exporter#14]
Hi,

So I successfully deployed the Exporter and set it up with no secure check (INSECURE_SKIP_VERIFY). 
When I try to do a get on the metrics with CURL I get a 500 error, looks like generated by the Exporter, not the SF Endpoint.
I tried as well setting up the SF Exporter as Prometheus DataSource and getting 404 on that side. 

Would it be possible to troubleshoot this issue? Let me know if you need any more feedback/testing on my side. Please see below an excerpt of the Error output
p.s: The same issue occurs with an account which has only read rights or the full admin one

<img width="880" alt="sf_exporter_500Error" src="https://user-images.githubusercontent.com/63010694/78166886-8440ce00-741b-11ea-9165-b45774708de9.png">

**Comment by mjavier2k** [comment]
Hi,

A couple of things to check

- What version of SF are you using? The exporter is tested on SF version
11.3 API
- Can you confirm that the ENV variables are set properly? You should be
seeing something like this on the exporter startup

Mar 23 18:11:50 promserver systemd[1]: Started Prometheus Solidfire
Exporter.
Mar 23 18:11:50 promserver solidfire-exporter[4074]: Mon Mar 23 18:11:50
 [INFO ] Version:
Mar 23 18:11:50 promserver solidfire-exporter[4074]: Mon Mar 23 18:11:50
 [INFO ] Built:
Mar 23 18:11:50 promserver solidfire-exporter[4074]: Mon Mar 23 18:11:50
 [INFO ] initializing new solidfire collector
Mar 23 18:11:50 promserver solidfire-exporter[4074]: Mon Mar 23 18:11:50
 [INFO ] initializing new solidfire client
Mar 23 18:11:50 promserver solidfire-exporter[4074]: Mon Mar 23 18:11:50
 [WARN ] TLS certificate verification is currently disabled - This is not
recommended.
Mar 23 18:11:50 promserver solidfire-exporter[4074]: Mon Mar 23 18:11:50
 [INFO ] *RPC Server: https://10.199.1.228/json-rpc/11.3
<https://10.199.1.228/json-rpc/11.3>*
Mar 23 18:11:50 promserver solidfire-exporter[4074]: Mon Mar 23 18:11:50
 [INFO ] Booted and listening on 0.0.0.0:9987/metrics

-  What user rights does your user have? Must have this so it report QoS
related metrics properly.

[image: image.png]

Let me know.






*CONFIDENTIALITY NOTICE:* This transmission contains confidential
information. The information is intended only for the use of the recipient
named above. If you have received this e-mail in error, please notify me
immediately and delete this file/message from your system. You are hereby
notified that any disclosure, copying, distribution, or the taking of any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by mjavier2k** [comment]
Hi,

A couple of things to check

- What version of SF are you using? The exporter is tested on SF version
11.3 API
- Can you confirm that the ENV variables are set properly? You should be
seeing something like this on the exporter startup


```
Mar 23 18:11:50 promserver solidfire-exporter[4074]: Mon Mar 23 18:11:50
 [WARN ] TLS certificate verification is currently disabled - This is not
recommended.
Mar 23 18:11:50 promserver solidfire-exporter[4074]: Mon Mar 23 18:11:50
 [INFO ] *RPC Server: https://10.199.1.228/json-rpc/11.3
<https://10.199.1.228/json-rpc/11.3>*
Mar 23 18:11:50 promserver solidfire-exporter[4074]: Mon Mar 23 18:11:50
 [INFO ] Booted and listening on 0.0.0.0:9987/metrics
```



-  What user rights does your user have? Must have this so it report QoS
related metrics properly.

![image](https://user-images.githubusercontent.com/22145/78171945-dd5c3200-741a-11ea-8390-b55964e2ac47.png)


Let me know.

**Comment by apollondor** [comment]
Hi Marvin,
Thanks for your quick reply.

1. API Version
Yes, on 11.3

2. ENV variables
They look to be set properly:
```
SOLIDFIRE_USER=***
SOLIDFIRE_PASS=***
SOLIDFIRE_RPC_ENDPOINT=https://***/json-rpc/11.3
INSECURE_SKIP_VERIFY=true
PORT=9987
```

And the startup output:
```
$ docker run --env-file=.env_file --rm -p 9987:9987 mjavier/solidfire-exporter:latest
Wed Apr 1 18:28:36  [INFO ] Version:
Wed Apr 1 18:28:36  [INFO ] Built:
Wed Apr 1 18:28:36  [INFO ] initializing new solidfire collector
Wed Apr 1 18:28:36  [INFO ] initializing new solidfire client
Wed Apr 1 18:28:36  [WARN ] TLS certificate verification is currently disabled - This is not recommended.
Wed Apr 1 18:28:36  [INFO ] RPC Server: https://***/json-rpc/11.3
Wed Apr 1 18:28:36  [INFO ] Booted and listening on 0.0.0.0:9987/metrics
```

3. User Rights
Yeap, it has all of them checked. And as mentioned before I even tried the admin one and it gets same issue.

**Comment by mjavier2k** [comment]
Can you try running this from your end and see if you are getting a reply?

curl -ksv -XPOST -u user:password --data
'{"id":1,"method":"ListAllNodes","params":{}}' https://x.x.x.x/json-rpc/11.3

Marvin

*CONFIDENTIALITY NOTICE:* This transmission contains confidential
information. The information is intended only for the use of the recipient
named above. If you have received this e-mail in error, please notify me
immediately and delete this file/message from your system. You are hereby
notified that any disclosure, copying, distribution, or the taking of any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by apollondor** [comment]
Yes, I do have access with a successful, complete output of the list of nodes to the SF endpoint from that VM, sorry forgot to mention that.

**Comment by mjavier2k** [comment]
I'm able to reproduce the issue locally with the docker image. I'll check
that later and get back to you.

Thanks!


*CONFIDENTIALITY NOTICE:* This transmission contains confidential
information. The information is intended only for the use of the recipient
named above. If you have received this e-mail in error, please notify me
immediately and delete this file/message from your system. You are hereby
notified that any disclosure, copying, distribution, or the taking of any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by apollondor** [comment]
Great thnx!

**Comment by mjavier2k** [comment]
@apollondor can you try pulling the latest image and see if that works for you?

**Comment by apollondor** [comment]
Hi Marvin,
Yes, it worked. Thnx for the great support!

On an aside note, not related to this issue. Besides exporting the SF data as Prometheus metrics have you tried making it useful, like importing it in other graphing tools like Grafana? 
I've tried doing that on my side and it doesn't work, because it seems in a standard integration of Grafana -> Prometheus, polling is done through its base "/" URL, which the Prometheus instance seems to be handling it by either forwarding to the /metrics one or smth else. 
Does this mean that a Prometheus instance should be used, where the SF Exporter would just collect and dump the metrics to one of its folders?

If you have any suggestion I'd be happy to hear, but if not still thanks for the previous support.

**Comment by mjavier2k** [comment]
I'm glad it is working for you now.

Yeah I have been using the metrics exposed by the exporter and presenting the data in Grafana. I added some example dashboard and prometheus scrape config in the repo yesterday. Give that a try and let me know. 

This is how your setup should look like. 

solidfire api -----> solidfire-exporter ----> prometheus ----> grafana

**Comment by apollondor** [comment]
Cool I'll check it out then, thnx!
