### ISSUE TITLE
Deploy on Kubernetes | error Curl (52) Empty reply from server

### ISSUE THREAD

**Issue by arunbpt7** [mjavier2k/solidfire-exporter#33]
Hello,

I am trying to run it on kubernetes as a deployment. some reason not getting the metrics on prometheus.

Is there any best practice  to be followed inorder to  run on  kubernetes?

**Comment by arunbpt7** [comment]
details are attached . running solidfire-exporter as a deployment and injecting the values as env. pod is getting up and running fine  getting "Empty reply from server" when curl the endpoint  and port. Please find thge screen shot attached.

We have restriction to run container as root user. So the deployment i defined to run as user 99. Does the exporter required to be run as root user?

![Image 3](https://user-images.githubusercontent.com/18433900/100241303-8eab5d00-2f01-11eb-8b98-e00c772f50eb.jpeg)
![Image](https://user-images.githubusercontent.com/18433900/100241307-8f43f380-2f01-11eb-856e-8f7413fed0ed.jpeg)

**Comment by mjavier2k** [comment]
Hey there @arunbpt7 

- can you describe what your setup is? deployment and service?
- are there any logs from the pod?
- can you try doing a port forward on the pod and curl localhost:9987/metrics and see what you get?

**Comment by arunbpt7** [comment]
It works now . The issue was with the environment variable pattern.

**Comment by mjavier2k** [comment]
Great! 👍
