### ISSUE TITLE
Can the exporter deploy for query multiple Solidfire API 

### ISSUE THREAD

**Issue by arunbpt7** [mjavier2k/solidfire-exporter#34]
Hello,
This is pretty good  tool and would like to adapt in to the firm.
The use case are as below.

We have multiple kubernetes clusters  in different ENV (dev,test,prod) use trident as the dynamic provisioner and use  multiple solidfires as backend respectevely . So i would like to monitor  all the solifire API using the  exporter.

1. is there any option to monitor multiple SOLIDFIRE API in a single deployment?
2. We use promethues operator which take the advantage of Servicemonitor to scrap the metrics. I deployed the solidfire exporter as a Kube deployment , created service  and servicemonitor to allow the promethues to scrap the metrics. 
As per the instruction given in the README  , the Prometheus Configuration has a  set label  as  "sfcluster: sfcluster01".which can be used in the grafana dashbaord configuration. In my case the ServiceMonitor Doesnt set that hence the metrics missing the sfcluster values and the dashboard is not functioning as expected. Is there any option to fix this.

**Comment by neufeldtech** [comment]
Hey @arunbpt7,

1) Regarding your multi-tenancy question.
At the present time, this exporter is setup for a single Solidfire cluster per exporter. In production, we run one exporter per Solidfire cluster as we have one Solidfire per datacenter, so it made sense for us to have one exporter in DC1 and one in DC2 localized to each Solidfire cluster.

In your particular situation, it sounds like it might be a good pattern to deploy one exporter per K8s cluster, then have this exporter scrape the Solidfire instance that is serving the particular K8s cluster. If I'm not understanding your desired deployment strategy and you have a fundamental reason that you want to only use one exporter rather than one per Solidfire cluster (cost, resource usage, etc), please let us know.

Making a change to support multiple Solidfire clusters per exporter would be a major breaking change to the config file syntax as well as the scrape configuration.

2) Regarding your question about the dashboard, I'll let @mjavier2k speak to it directly, but I'm going to create a new issue to track putting together a Grafana app to share other (and updated) dashboards that we've created and find useful for this exporter.

**Comment by neufeldtech** [comment]
@arunbpt7 ,

I don't have much experience with `ServiceMonitor` but maybe this is what you're looking for?

[Apparently this is how to add additional labels to ServiceMonitor k8s resources](https://stackoverflow.com/questions/63852779/how-to-set-a-label-in-service-monitor-so-it-appears-in-prometheus-metrics)

```yaml
kind: Service
apiVersion: v1
metadata:
  name: solidfire-exporter
  labels:
    app: solidfire-exporter
    sfcluster: sfcluster01
spec:
  selector:
    app: solidfire-exporter
  ports:
  - name: exporter-port
    port: 9999
```

**Comment by arunbpt7** [comment]
> ```yaml
> solidfire
> ```

@neufeldtech Thanks for the response , this is excelent, it works and i am anble to see the sfcluster labels in the metrics and the dashboard seems to be fine now.Thanks for the quick response

**Comment by arunbpt7** [comment]
> Hey @arunbpt7,
> 
> 1. Regarding your multi-tenancy question.
>    At the present time, this exporter is setup for a single Solidfire cluster per exporter. In production, we run one exporter per Solidfire cluster as we have one Solidfire per datacenter, so it made sense for us to have one exporter in DC1 and one in DC2 localized to each Solidfire cluster.
>    In your particular situation, it sounds like it might be a good pattern to deploy one exporter per K8s cluster, then have this exporter scrape the Solidfire instance that is serving the particular K8s cluster. If I'm not understanding your desired deployment strategy and you have a fundamental reason that you want to only use one exporter rather than one per Solidfire cluster (cost, resource usage, etc), please let us know.
>    Making a change to support multiple Solidfire clusters per exporter would be a major breaking change to the config file syntax as well as the scrape configuration.
> 2. Regarding your question about the dashboard, I'll let @mjavier2k speak to it directly, but I'm going to create a new issue to track putting together a Grafana app to share other (and updated) dashboards that we've created and find useful for this exporter.

@neufeldtech 

Thanks for the confirmation. there are multiple solidfire in the DC's are to be monitored. 
The K8s clusters are also large numbers and across the DC's and possible expand the capacity in near future. Running exporter per clusters is not a good idea interms of resource costs and other factors. 
for time being i think it is a best practice to run the exporter per DC .

**Comment by arunbpt7** [comment]
1. is there any documentation available for the metrics to understand them better?
2. Is there any metrics available to see the total size of solidfire available to use?

**Comment by mjavier2k** [comment]
hey there @arunbpt7 ,

1) the exporter is based on this version of the solidfire API - https://library.netapp.com/ecm/ecm_download_file/ECMLP2856155. Check that out for details on the metrics

2) These are the possible metrics that you maybe looking for

solidfire_cluster_capacity_max_used_space
solidfire_cluster_capacity_unique_blocks_used_space
solidfire_cluster_capacity_provisioned_space

I'll be updating soon the example dashboards on #37 that will include the above metrics.

**Comment by arunbpt7** [comment]
> hey there @arunbpt7 ,
> 
> 1. the exporter is based on this version of the solidfire API - https://library.netapp.com/ecm/ecm_download_file/ECMLP2856155. Check that out for details on the metrics
> 2. These are the possible metrics that you maybe looking for
> 
> solidfire_cluster_capacity_max_used_space
> solidfire_cluster_capacity_unique_blocks_used_space
> solidfire_cluster_capacity_provisioned_space
> 
> I'll be updating soon the example dashboards on #37 that will include the above metrics.

@mjavier2k  Excelent , Thanks for the quick response.
Its an awsome work. Thanks for that

**Comment by neufeldtech** [comment]
@arunbpt7  - you may find links to additional dashboards here https://github.com/mjavier2k/solidfire-exporter#grafana-dashboards

**Comment by scaleoutsean** [comment]
> The K8s clusters are also large numbers and across the DC's and possible expand the capacity in near future. Running exporter per clusters is not a good idea interms of resource costs and other factors.

Seriously? Can you substantiate that claim?

On a 2 vCPU, 8 GB vRAM system two instances of solidfire-exporter are consuming negligible amount of resources.

![image](https://user-images.githubusercontent.com/16622642/121018094-a0cf5780-c7d0-11eb-96c1-1c8edfd79f38.png)
