### ISSUE TITLE
Test ElementOS 12

### ISSUE THREAD

**Issue by neufeldtech** [mjavier2k/solidfire-exporter#42]
Using the [SolidFire Test VMs](https://github.com/scaleoutsean/awesome-solidfire#solidfireelement-demo-vm), document in the README which versions of the SolidFire API work as expected with this exporter.
- [x] v11 is already validated as working
- [x] v12 has not yet been validated, but @scaleoutsean tells me that it should be fine

**Comment by scaleoutsean** [comment]
Element Python SDK Release Notes v1.7 released few months back (support login required) [lists](https://mysupport.netapp.com/site/tools/tool-eula/elem-python-sdk/download) approximately 15 new API methods and one removed API method (`CheckPingOnVlan`; even that one may still be available without SDK, but I haven't checked that). 

So it's pretty safe to say that 

- v12.[0,1,2] should all be fine
- Users of SolidFire clusters running v12 can point solidfire-exporter to a v11.x API endpoint 

But I'll give it a try on my SF 12.2 VM. Is there a formal method or just run the container and grep the docker log for errors?

**Comment by neufeldtech** [comment]
@scaleoutsean any _formal method_ is still currently "emerging" ;) 

I was planning on the testing for now being as boiled down to:
- Booting the exporter
- Running a collection against a v12 demo VM
- Checking logs for any obvious errors
- Doing sanity check against metrics
- Checking `_up` metric

After that base functionality is verified, I'd feel fine about publishing a small compatibility matrix to the README (which should also contain the notes about which pieces of functionality require and ADMIN user, etc).

In the future, I'm envisioning the following enhancements to this project:
- Docker-compose test setup containing Prometheus, Grafana (with dashboards provisioned), Solidfire-Exporter where it's easy to point to any SF api VM or installation to manually test functionality
- Enhancements to the exporter around enabling/disabling the various 'collection' components via CMDline/config flags so that users can choose to enable/disable features such as QOS histograms, or volume details (since some types of metrics could get quite verbose)

**Comment by scaleoutsean** [comment]
No problem! 

Did a quick run, saw no errors related to the API v12.2. Can't see anything wrong.

- Config

```yaml
listen:
  address: 127.0.0.1:9987
client:
  endpoint: https://192.168.1.30/json-rpc/12.2
  username: admin
  password: admin
  insecure: true
  timeout: 30
```

- Run

```raw
$ ./bin/solidfire-exporter -c config.yaml
Tue Mar 9 22:39:56  [INFO ] Found configuration file on /home/sean/code/solidfire-exporter/config.yaml 
Tue Mar 9 22:39:56  [INFO ] Version: 2f6eabd703a587fbe65aa2d06399814fa8613a61
Tue Mar 9 22:39:56  [INFO ] Built: 2021-03-09_22:38:31
Tue Mar 9 22:39:56  [INFO ] initializing new solidfire collector
Tue Mar 9 22:39:56  [INFO ] initializing new solidfire client
Tue Mar 9 22:39:56  [WARN ] TLS certificate verification is currently disabled - This is not recommended.
Tue Mar 9 22:39:56  [INFO ] RPC Server: https://192.168.1.30/json-rpc/12.2
Tue Mar 9 22:39:56  [INFO ] Config setting found for client.insecure: true
Tue Mar 9 22:39:56  [INFO ] Config setting found for client.timeout: 30
Tue Mar 9 22:39:56  [INFO ] Config setting found for client.endpoint: https://192.168.1.30/json-rpc/12.2
Tue Mar 9 22:39:56  [INFO ] Config setting found for config: config.yaml
Tue Mar 9 22:39:56  [INFO ] Config setting found for listen.address: 127.0.0.1:9987
Tue Mar 9 22:39:56  [INFO ] Config setting found for client.username: admin
Tue Mar 9 22:39:56  [INFO ] Config setting found for client.password: [REDACTED]
Tue Mar 9 22:39:56  [INFO ] Booted and listening on 127.0.0.1:9987/metrics

```

- Scrape & visualize

![image](https://user-images.githubusercontent.com/16622642/110489463-63ecb980-812a-11eb-830d-3b08553bcad0.png)

- Log (LGTM)

https://gist.github.com/scaleoutsean/b7a24c9a4ce3f96768e74e94cfd4da05

- `solidfire_up` is up
- Several NaNs (not related to API v12.2 I think - see in the Gist but I'll open another issue fo rthat)

- SolidFire Demo VM v12.2
 
![image](https://user-images.githubusercontent.com/16622642/110490097-f1c8a480-812a-11eb-8a08-c26c0f66ff74.png)

![image](https://user-images.githubusercontent.com/16622642/110490560-6ac7fc00-812b-11eb-9fa1-593e51b1b741.png)

**Comment by neufeldtech** [comment]
Thanks for assisting with this testing @scaleoutsean !
