### ISSUE TITLE
NaNs in capacity-related metrics

### ISSUE THREAD

**Issue by scaleoutsean** [mjavier2k/solidfire-exporter#43]
- v0.5.1
- SF Demo VM v12.2
- Issue: efficiency shouldn't be 0
```
solidfire_cluster_capacity_compression_factor NaN
solidfire_cluster_capacity_de_duplication_factor NaN
solidfire_cluster_capacity_efficiency_factor NaN
```

Non-real world environments like SF Demo VM can helps you discover some edge cases :-) 

In HCICollector I think I even added an `if $eff < 1x then $eff = 1x` kind of dirty trick. It's even possible to have efficiency below 1x  (I think on a small volume with low efficiency and several snapshots, or something like that). Or zero, when there's nothing.

Anyway, what I have is a VM with SolidFire Demo v12.2 and 1 volume. The volume has no data and no snaps.

Maybe you hit divide by zero? 

![image](https://user-images.githubusercontent.com/16622642/110493826-f17dd880-812d-11eb-9204-d30ebf56aaa4.png)

```pwsh
> Get-SFClusterCapacity

ActiveBlockSpace             : 10041361337
ActiveSessions               : 1
AverageIOPS                  : 0
ClusterRecentIOSize          : 0
CurrentIOPS                  : 0
MaxIOPS                      : 3000
MaxOverProvisionableSpace    : 18554258718720
MaxProvisionedSpace          : 3710851743744
MaxUsedMetadataSpace         : 14495514624
MaxUsedSpace                 : 161061273600
NonZeroBlocks                : 0
PeakActiveSessions           : 1
PeakIOPS                     : 1
ProvisionedSpace             : 1073741824
SnapshotNonZeroBlocks        : 0
Timestamp                    : 2021-03-09T15:23:49Z
TotalOps                     : 17438604
UniqueBlocks                 : 0
UniqueBlocksUsedSpace        : 0
UsedMetadataSpace            : 0
UsedMetadataSpaceInSnapshots : 0
UsedSpace                    : 0
ZeroBlocks                   : 262144
```

**Comment by neufeldtech** [comment]
Reproduced with Demo VM v11

```
# HELP solidfire_cluster_capacity_de_duplication_factor The cluster deDuplication factor. deDuplicationFactor = (nonZeroBlocks + snapshotNonZeroBlocks) / uniqueBlocks
# TYPE solidfire_cluster_capacity_de_duplication_factor gauge
solidfire_cluster_capacity_de_duplication_factor NaN
# HELP solidfire_cluster_capacity_efficiency_factor The cluster efficiency factor. efficiencyFactor = thinProvisioningFactor * deDuplicationFactor * compressionFactor
# TYPE solidfire_cluster_capacity_efficiency_factor gauge
solidfire_cluster_capacity_efficiency_factor NaN
```

**Comment by neufeldtech** [comment]
Found the following in my notes in the repo:

GetClusterCapacity
You can use the GetClusterCapacity to return high-level capacity measurements for an entire
storage cluster. This method returns fields that you can use to calculate the efficiency rates shown in
the Element web UI. You can use the efficiency calculations in scripts to return the efficiency rates
for thin provisioning, deduplication, compression, and overall efficiency.
Efficiency calculations
Use the following equations to calculate thin provisioning, deduplication, and compression. These equations apply to Element 8.2 and later.
• thinProvisioningFactor = (nonZeroBlocks + zeroBlocks) / nonZeroBlocks
• deDuplicationFactor = (nonZeroBlocks + snapshotNonZeroBlocks) / uniqueBlocks
• compressionFactor = (uniqueBlocks * 4096) / (uniqueBlocksUsedSpace * 0.93)

Overall efficiency rate calculation
Use the following equation to calculate overall cluster efficiency using the results of the thin provisioning, deduplication, and compression efficiency calculations.
• efficiencyFactor = thinProvisioningFactor * deDuplicationFactor * compressionFactor

===

Dividing by zero seems to be what's happening here...

Perhaps an appropriate hack for now is to fallback to `1` if we hit a NaN for thinprovisioning, dedupe, or compression factors. This would at least line up with what the UI shows on an empty cluster

![image](https://user-images.githubusercontent.com/8252744/110740079-09ba2a00-81f8-11eb-9879-47eb959bdadd.png)

**Comment by scaleoutsean** [comment]
In sfcollector in [assume](https://github.com/scaleoutsean/hcicollector/blob/e30652c0e72f46937f049c7e44e3f8d5516a7b40/sfcollector/solidfire_graphite_collector.py#L108) 1x when there's no data.
